project_name: 'MANet'
experiment_name: 'MANet-0119' # TODO: may be updated

training:
  max_epochs: 10000
  validation_freq: 1000 # TODO: may be updated
  checkpoint_freq: 2000 # TODO: may be updated
  wandb_id: 'ad465hf4' # TODO: may be updated

model:
  name: 'MANet'
  gpu: True
  is_data_parallel: True
  network:
    name: 'MANet_s1'
    in_nc: 1
    scale: 1
    kernel_size: 33
    manet_nf: 128
    manet_nb: 1
    split: 2
    init: ['xavier_normal', 0.1, 'normal']
  optimizer:
    name: 'Adam'
    lr: 2e-4
    weight_decay: 1e-8
  scheduler:
    name: 'CosineAnnealingWarmRestarts'
    T_0: 10000
    T_mult: 1.25
    eta_min: 1e-7
  loss_function:
    name: 'L1'
  checkpoint:
    network: './'
    training_state: ~

train_data:
  name: 'HrLrKernelFromBioSR'
  is_train: True
  gpu_id: ~
  repeat: 64  # ~ for no repeat
  img_filter:
    img_root: '../BioDataset/Mixed'
    structure_selected: [1, 2, 3, 4]
    included_idx: [11, 100]
  hr_cropping:
    mode: 'random' # TODO: may be updated
    center_pos: [-1, -1]
    scanning_shape: [-1, -1]
    hr_size: [264, 264] # TODO: may be updated
  img_signal: [100, 1000]
  psf_settings:
      kernel_size: 33
      NA: 1.35
      Lambda: 0.525
      RefractiveIndex: 1.33
      SigmaX: 2.0
      SigmaY: 2.0
      Pixelsize: 0.0313
      nMed: 1.33
      phaseZ:
          idx_start: 4
          num_idx: 15
          mode: 'gaussian'
          std: 0.125
          bound: 1.0
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
      mode: 'circular'  # constant | reflect | replicate | circular
      value: -1  # for constant mode
  loader_settings:
    batch_size: 2 # TODO: may be updated
    shuffle: True
    num_workers: 4
    pin_memory: False
    drop_last: True

test_data:
  name: 'HrLrKernelFromBioSR'
  is_train: False
  gpu_id: ~
  repeat: ~  # ~ for no repeat
  img_filter:
    img_root: '../BioDataset/Mixed'
    structure_selected: [1, 2, 3, 4]
    included_idx: [1, 10]
  hr_cropping:
    mode: 'random' # TODO: may be updated
    center_pos: [-1, -1]
    scanning_shape: [-1, -1]
    hr_size: [264, 264] # TODO: may be updated
  img_signal: [1000]
  psf_settings:
      kernel_size: 33
      NA: 1.35
      Lambda: 0.525
      RefractiveIndex: 1.33
      SigmaX: 2.0
      SigmaY: 2.0
      Pixelsize: 0.0313
      nMed: 1.33
      phaseZ:
          idx_start: 4
          num_idx: 15
          mode: 'gaussian'
          std: 0.125
          bound: 1.0
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
      mode: 'circular'  # constant | reflect | replicate | circular
      value: -1  # for constant mode
  loader_settings:
    batch_size: 1
    shuffle: False
    num_workers: 0
    pin_memory: False
    drop_last: False
