project_name: 'IKC'
experiment_name: 'IKC-0130-pca65' # TODO: may be updated

training:
  max_epochs: 10000
  correct_step: 7
  validation_freq: 100 # TODO: may be updated
  checkpoint_freq: 200 # TODO: may be updated
  wandb_id: '9871ud65' # TODO: may be updated

F_model:
  name: 'F_Model'
  gpu: True
  is_data_parallel: False
  pca_mean: './data/pca_matrices/pca_mean.pth'
  pca_matrix: './data/pca_matrices/pca_matrix65.pth'
  network:
    name: 'SFTMD'
    in_nc: 1
    out_nc: 1
    nf: 64
    nb: 16
    scale: 2
    input_para: 65
    min: 0.0
    max: 1.0
    init: ~
  optimizer:
    name: ~
  scheduler:
    name: ~
  loss_function:
    name: 'MSE'
  checkpoint:
    network: './experiments/SFTMD-0130-pca65/54000_network.pth' # TODO: may be updated
    training_state: ~

P_model:
  name: 'P_Model'
  gpu: True
  is_data_parallel: False
  pca_mean: './data/pca_matrices/pca_mean.pth'
  pca_matrix: './data/pca_matrices/pca_matrix65.pth'
  network:
    name: 'Predictor'
    in_nc: 1
    nf: 64
    code_len: 65
    use_bias: True
    init: ['orthogonal', 0.2, 'uniform']
  optimizer:
    name: 'Adam'
    lr: 1e-4
    weight_decay: 0.0
  scheduler:
    name: ~
  loss_function:
    name: 'MSE'
  checkpoint:
    network: ~
    training_state: ~

C_model:
  name: 'C_Model'
  gpu: True
  is_data_parallel: False
  network:
    name: 'Corrector'
    in_nc: 1
    nf: 64
    code_len: 65
    use_bias: True
    init: ['orthogonal', 0.2, 'uniform']
  optimizer:
    name: 'Adam'
    lr: 1e-4
    weight_decay: 0.0
  scheduler:
    name: ~
  loss_function:
    name: 'MSE'
  checkpoint:
    network: ~
    training_state: ~

train_data:
  name: 'HrLrKernelFromBioSR'
  is_train: True
  gpu_id: ~
  repeat: ~  # ~ for no repeat
  img_filter:
    img_root: '../BioDataset/Mixed'
    structure_selected: [1, 2, 3, 4]
    included_idx: [11, 100]
  hr_crop:
    mode: 'random' # TODO: may be updated
    center_pos: [-1, -1]
    scan_shape: [-1, -1]
    hr_size: [264, 264] # TODO: may be updated
  scale: 2 # TODO: may be updated
  img_signal: [100, 1000]
  psf_settings:
      kernel_size: 33
      NA: 1.35
      Lambda: 0.525
      RefractiveIndex: 1.33
      SigmaX: 2.0
      SigmaY: 2.0
      Pixelsize: 0.0313
      nMed: 1.33
      phaseZ:
          idx_start: 4
          num_idx: 15
          mode: 'gaussian'
          std: 0.125
          bound: 1.0
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
      mode: 'circular'  # constant | reflect | replicate | circular
      value: -1  # for constant mode
  loader_settings:
    batch_size: 8 # TODO: may be updated
    shuffle: True
    num_workers: 4
    pin_memory: False
    drop_last: True

test_data:
  name: 'HrLrKernelFromBioSR'
  is_train: False
  gpu_id: ~
  repeat: ~  # ~ for no repeat
  img_filter:
    img_root: '../BioDataset/Mixed'
    structure_selected: [1, 2, 3, 4]
    included_idx: [1, 10]
  hr_crop:
    mode: 'random' # TODO: may be updated
    center_pos: [-1, -1]
    scan_shape: [-1, -1]
    hr_size: [264, 264] # TODO: may be updated
  scale: 2 # TODO: may be updated
  img_signal: [1000]
  psf_settings:
      kernel_size: 33
      NA: 1.35
      Lambda: 0.525
      RefractiveIndex: 1.33
      SigmaX: 2.0
      SigmaY: 2.0
      Pixelsize: 0.0313
      nMed: 1.33
      phaseZ:
          idx_start: 4
          num_idx: 15
          mode: 'gaussian'
          std: 0.125
          bound: 1.0
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
      mode: 'circular'  # constant | reflect | replicate | circular
      value: -1  # for constant mode
  loader_settings:
    batch_size: 1
    shuffle: False
    num_workers: 0
    pin_memory: False
    drop_last: False
